# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task -l

  asdf:
    desc: Install asdf package manager
    cmds:
      - git clone https://github.com/asdf-vm/asdf.git ~/.asdf

  fzf:
    desc: Install fzf command-line fuzzy finder
    cmds:
      - git -C ~/.fzf pull 2>/dev/null || git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install

  atuin:
    desc: Atuin for magical shell history
    cmds:
      - bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)

  lsp:
    desc: Install TailwindCSS and vscode language servers
    cmds:
      - npm install -g @tailwindcss/language-server vscode-langservers-extracted

  vivid:
    desc: Install themeable LS_COLORS generator
    dir: /tmp
    vars:
      VERSION: 0.10.1
    cmds:
      - wget "https://github.com/sharkdp/vivid/releases/download/v{{.VERSION}}/vivid_{{.VERSION}}_amd64.deb"
      - sudo dpkg -i vivid_{{.VERSION}}_amd64.deb

  gems:
    desc: Install gems for Ruby on Rails development
    cmds:
      - gem update --system
      - gem install easy_translate erb_lint i18n-tasks neovim
          rubocop rubocop-minitest rubocop-performance rubocop-rails rubocop-rails-omakase
          ruby-lsp ruby-lsp-rails

  tools:
    desc: Install my daily dev tools with flox
    cmds:
      - flox install ast-grep bat difftastic eza fastfetch fd go-task hyperfine
          jemalloc jq just lazygit ripgrep stow universal-ctags xan xh xplr zoxide

  chromedriver:
    desc: Pull latest chromedriver to WindowsApps directory
    dir: /tmp
    vars:
      VERSION:
        sh: curl https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json | jq -r '.channels.Stable.version'
    cmds:
      - curl https://storage.googleapis.com/chrome-for-testing-public/{{.VERSION}}/win64/chromedriver-win64.zip -o chromedriver.zip
      - unzip -u chromedriver.zip
      - mv -v chromedriver-win64/chromedriver.exe "`readlink $(which chromedriver)`"
