#!/usr/bin/env bash
export SXHKD_SHELL=/bin/sh
export PATH=$PATH:~/.dotfiles/bin:/usr/lib/gnome-settings-daemon:/opt/dropbox

bspc config window_gap         15
bspc config border_width        3
bspc config split_ratio         0.52

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true
bspc config auto_cancel           true

bspc monitor VGA1 -d 1 2 3 4
bspc monitor HDMI1 -d 5 6 7 8

bspc rule -a Firefox desktop=^1 focus=on
bspc rule -a Skype desktop=^2 floating=on
bspc rule -a Steam desktop=^3
bspc rule -a URxvt desktop=^5

gnome-settings-daemon &
feh --bg-fill ~/Pictures/6Z8WnzT.png &
xrdb -merge ~/.Xresources &
xset -b &
skype &
firefox &
urxvt &
sxhkd &
panel &
compton -b
