[settings]

[settings.ruby]
compile = false

[tools]
atuin = "latest"
bat = "latest"
btop = { version = "latest", os = ["linux"] }
difftastic = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lua-language-server = "latest"
neovim = "0.12.2"
node = "22.12.0"
"npm:@olrtg/emmet-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@herb-tools/language-server" = "latest"
"npm:@herb-tools/linter" = "latest"
"npm:@herb-tools/formatter" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:prettier" = "latest"
"npm:wsl-open" = "latest"
opencode = "latest"
ripgrep = "latest"
ruby = "4.0.3"
stylua = "latest"
tree-sitter = "latest"
usage = "latest"
vivid = { version = "latest", os = ["linux"] }
watchexec = "latest"
zoxide = "latest"
oxfmt = "latest"
oxlint = "latest"
task = "latest"
github-cli = "latest"
gitleaks = "latest"
"github:axllent/mailpit" = "latest"
"github:medialab/xan" = "latest"

# https://github.com/protonpass/pass-cli/blob/main/CHANGELOG.md
"http:pass-cli" = {
  version = "1.8.0",
  version_list_url = "https://api.github.com/repos/protonpass/pass-cli/tags",
  version_json_path = ".[].name",
  url = "https://proton.me/download/pass-cli/{{ version }}/pass-cli-{{os()}}-{{arch(x64='x86_64', arm64='aarch64')}}",
  bin = "pass-cli"
}
